version: asmjit-{build}

image: Visual Studio 2015
clone_folder: c:\dev\asmjit

environment:
  matrix:
    - BUILD_TYPE: Debug
      TOOLCHAIN: "Visual Studio 10"

    - BUILD_TYPE: Release
      TOOLCHAIN: "Visual Studio 10"

    - BUILD_TYPE: Debug
      TOOLCHAIN: "Visual Studio 10 Win64"

    - BUILD_TYPE: Release
      TOOLCHAIN: "Visual Studio 10 Win64"

    - BUILD_TYPE: Debug
      TOOLCHAIN: "Visual Studio 12"

    - BUILD_TYPE: Release
      TOOLCHAIN: "Visual Studio 12"

    - BUILD_TYPE: Debug
      TOOLCHAIN: "Visual Studio 12 Win64"

    - BUILD_TYPE: Release
      TOOLCHAIN: "Visual Studio 12 Win64"

    - BUILD_TYPE: Debug
      TOOLCHAIN: "Visual Studio 14"

    - BUILD_TYPE: Release
      TOOLCHAIN: "Visual Studio 14"

    - BUILD_TYPE: Debug
      TOOLCHAIN: "Visual Studio 14 Win64"

    - BUILD_TYPE: Release
      TOOLCHAIN: "Visual Studio 14 Win64"

build_script:
  - cd c:\dev\asmjit
  - md build
  - cd build
  - cmake .. -G"%TOOLCHAIN%" -DASMJIT_BUILD_TEST=1
  - msbuild /m /nologo /v:quiet /p:Configuration=%BUILD_TYPE% asmjit.sln

test_script:
  - cd c:\dev\asmjit\build\%BUILD_TYPE%
  - asmjit_test_unit.exe
  - asmjit_test_x86.exe
